# -*- coding: utf-8 -*-

# Form implementation generated from reading ui file 'Rocpy.ui'
#
# Created by: PyQt5 UI code generator 5.15.4
#
# WARNING: Any manual changes made to this file will be lost when pyuic5 is
# run again.  Do not edit this file unless you know what you are doing.


from PyQt5 import QtCore, QtGui, QtWidgets


import matplotlib
from matplotlib.backends.backend_qt5agg import FigureCanvasQTAgg, NavigationToolbar2QT as NavigationToolbar
from matplotlib.figure import Figure
import matplotlib.pyplot as plt

from numpy import power,round
from queue import Queue


import utils as ut


matplotlib.use('TkAgg')


HB_in = {'value_sci': 30.0, 'value_mi': 10.0 , 'value_GSI': 50.0, 'value_D': 0.0, 'value_Ei': 12000.0,'value_MR': 400.0}
fail_in = {'value_appl': 'general','value_H': 50.0,'value_gamma':0.026,'value_s3max':7.5}
graph_opt = {'value_xres':5.0,'show_HB':2.0,'show_MC':0.0,'show_grid': 1}

HB_out = ut.calc_HB(HB_in)
mohr_out = ut.calc_MC(HB_in,fail_in,HB_out)
rockmass_out = ut.calc_rockm(HB_in,HB_out)




class pltCanvas(FigureCanvasQTAgg):

	def __init__(self,parent=None):


		self.fig= Figure()
		self.ax = self.fig.add_subplot(111)

		super(pltCanvas,self).__init__(self.fig)





class Ui_Rocpy(QtWidgets.QMainWindow):


	#@profile
	def updateGui(self):
		if self.inQueue.not_empty:
			try:
				self.consoleWindow.append(self.inQueue.get_nowait())
			except:
				True
	def setupUi(self, Rocpy):

		self.setWindowTitle('Rocpy')		
		self.inQueue = Queue()
		Rocpy.setObjectName("Rocpy")
		Rocpy.resize(1125, 719)
		sizePolicy = QtWidgets.QSizePolicy(QtWidgets.QSizePolicy.Expanding, QtWidgets.QSizePolicy.Expanding)
		sizePolicy.setHorizontalStretch(0)
		sizePolicy.setVerticalStretch(0)
		sizePolicy.setHeightForWidth(Rocpy.sizePolicy().hasHeightForWidth())
		Rocpy.setSizePolicy(sizePolicy)
		icon = QtGui.QIcon()
		icon.addPixmap(QtGui.QPixmap("icon/Rocpy.png"), QtGui.QIcon.Normal, QtGui.QIcon.Off)
		Rocpy.setWindowIcon(icon)
		self.main_window = QtWidgets.QWidget(Rocpy)
		self.main_window.setEnabled(True)
		sizePolicy = QtWidgets.QSizePolicy(QtWidgets.QSizePolicy.Expanding, QtWidgets.QSizePolicy.Expanding)
		sizePolicy.setHorizontalStretch(0)
		sizePolicy.setVerticalStretch(0)
		sizePolicy.setHeightForWidth(self.main_window.sizePolicy().hasHeightForWidth())
		self.main_window.setSizePolicy(sizePolicy)
		self.main_window.setObjectName("main_window")
		self.verticalLayout_3 = QtWidgets.QVBoxLayout(self.main_window)
		self.verticalLayout_3.setSizeConstraint(QtWidgets.QLayout.SetNoConstraint)
		self.verticalLayout_3.setObjectName("verticalLayout_3")
		self.main_grid = QtWidgets.QWidget(self.main_window)
		sizePolicy = QtWidgets.QSizePolicy(QtWidgets.QSizePolicy.Expanding, QtWidgets.QSizePolicy.Expanding)
		sizePolicy.setHorizontalStretch(0)
		sizePolicy.setVerticalStretch(0)
		sizePolicy.setHeightForWidth(self.main_grid.sizePolicy().hasHeightForWidth())
		self.main_grid.setSizePolicy(sizePolicy)
		self.main_grid.setObjectName("main_grid")
		self.gridLayout = QtWidgets.QGridLayout(self.main_grid)
		self.gridLayout.setSizeConstraint(QtWidgets.QLayout.SetNoConstraint)
		self.gridLayout.setObjectName("gridLayout")
		self.output_param = QtWidgets.QWidget(self.main_grid)
		sizePolicy = QtWidgets.QSizePolicy(QtWidgets.QSizePolicy.Fixed, QtWidgets.QSizePolicy.Fixed)
		sizePolicy.setHorizontalStretch(0)
		sizePolicy.setVerticalStretch(0)
		sizePolicy.setHeightForWidth(self.output_param.sizePolicy().hasHeightForWidth())
		self.output_param.setSizePolicy(sizePolicy)
		self.output_param.setObjectName("output_param")
		self.verticalLayout_2 = QtWidgets.QVBoxLayout(self.output_param)
		self.verticalLayout_2.setObjectName("verticalLayout_2")
		self.HB_crit = QtWidgets.QLabel(self.output_param)
		sizePolicy = QtWidgets.QSizePolicy(QtWidgets.QSizePolicy.Fixed, QtWidgets.QSizePolicy.Fixed)
		sizePolicy.setHorizontalStretch(0)
		sizePolicy.setVerticalStretch(0)
		sizePolicy.setHeightForWidth(self.HB_crit.sizePolicy().hasHeightForWidth())
		self.HB_crit.setSizePolicy(sizePolicy)
		self.HB_crit.setObjectName("HB_crit")
		self.verticalLayout_2.addWidget(self.HB_crit, 0, QtCore.Qt.AlignHCenter)
		self.frame_HBcrit = QtWidgets.QFrame(self.output_param)
		sizePolicy = QtWidgets.QSizePolicy(QtWidgets.QSizePolicy.Fixed, QtWidgets.QSizePolicy.Expanding)
		sizePolicy.setHorizontalStretch(0)
		sizePolicy.setVerticalStretch(0)
		sizePolicy.setHeightForWidth(self.frame_HBcrit.sizePolicy().hasHeightForWidth())
		self.frame_HBcrit.setSizePolicy(sizePolicy)
		self.frame_HBcrit.setFrameShape(QtWidgets.QFrame.Box)
		self.frame_HBcrit.setFrameShadow(QtWidgets.QFrame.Plain)
		self.frame_HBcrit.setObjectName("frame_HBcrit")
		self.verticalLayout_4 = QtWidgets.QVBoxLayout(self.frame_HBcrit)
		self.verticalLayout_4.setObjectName("verticalLayout_4")
		self.form_HBcrit = QtWidgets.QWidget(self.frame_HBcrit)
		sizePolicy = QtWidgets.QSizePolicy(QtWidgets.QSizePolicy.Fixed, QtWidgets.QSizePolicy.Fixed)
		sizePolicy.setHorizontalStretch(0)
		sizePolicy.setVerticalStretch(0)
		sizePolicy.setHeightForWidth(self.form_HBcrit.sizePolicy().hasHeightForWidth())
		self.form_HBcrit.setSizePolicy(sizePolicy)
		self.form_HBcrit.setObjectName("form_HBcrit")
		self.formLayout_8 = QtWidgets.QFormLayout(self.form_HBcrit)
		self.formLayout_8.setLabelAlignment(QtCore.Qt.AlignCenter)
		self.formLayout_8.setObjectName("formLayout_8")
		self.label_mb = QtWidgets.QLabel(self.form_HBcrit)
		self.label_mb.setObjectName("label_mb")
		self.formLayout_8.setWidget(1, QtWidgets.QFormLayout.LabelRole, self.label_mb)
		self.label_s = QtWidgets.QLabel(self.form_HBcrit)
		self.label_s.setObjectName("label_s")
		self.formLayout_8.setWidget(2, QtWidgets.QFormLayout.LabelRole, self.label_s)
		self.label_a = QtWidgets.QLabel(self.form_HBcrit)
		self.label_a.setObjectName("label_a")
		self.formLayout_8.setWidget(3, QtWidgets.QFormLayout.LabelRole, self.label_a)
		
		self.value_mb = QtWidgets.QLabel(self.form_HBcrit)
		self.value_mb.setObjectName("value_mb")
		self.formLayout_8.setWidget(1, QtWidgets.QFormLayout.FieldRole, self.value_mb)
		
		self.value_s = QtWidgets.QLabel(self.form_HBcrit)
		self.value_s.setObjectName("value_s")
		self.formLayout_8.setWidget(2, QtWidgets.QFormLayout.FieldRole, self.value_s)
		
		self.value_a = QtWidgets.QLabel(self.form_HBcrit)
		self.value_a.setObjectName("value_a")
		self.formLayout_8.setWidget(3, QtWidgets.QFormLayout.FieldRole, self.value_a)
		
		self.verticalLayout_4.addWidget(self.form_HBcrit)
		self.verticalLayout_2.addWidget(self.frame_HBcrit, 0, QtCore.Qt.AlignHCenter)
		self.MC_fit_2 = QtWidgets.QLabel(self.output_param)
		self.MC_fit_2.setObjectName("MC_fit_2")
		self.verticalLayout_2.addWidget(self.MC_fit_2, 0, QtCore.Qt.AlignHCenter)
		self.frame_MCfit = QtWidgets.QFrame(self.output_param)
		sizePolicy = QtWidgets.QSizePolicy(QtWidgets.QSizePolicy.Fixed, QtWidgets.QSizePolicy.Expanding)
		sizePolicy.setHorizontalStretch(0)
		sizePolicy.setVerticalStretch(0)
		sizePolicy.setHeightForWidth(self.frame_MCfit.sizePolicy().hasHeightForWidth())
		self.frame_MCfit.setSizePolicy(sizePolicy)
		self.frame_MCfit.setFrameShape(QtWidgets.QFrame.Box)
		self.frame_MCfit.setFrameShadow(QtWidgets.QFrame.Plain)
		self.frame_MCfit.setObjectName("frame_MCfit")
		self.verticalLayout_5 = QtWidgets.QVBoxLayout(self.frame_MCfit)
		self.verticalLayout_5.setObjectName("verticalLayout_5")
		self.Form_MCfit = QtWidgets.QWidget(self.frame_MCfit)
		sizePolicy = QtWidgets.QSizePolicy(QtWidgets.QSizePolicy.Fixed, QtWidgets.QSizePolicy.Fixed)
		sizePolicy.setHorizontalStretch(0)
		sizePolicy.setVerticalStretch(0)
		sizePolicy.setHeightForWidth(self.Form_MCfit.sizePolicy().hasHeightForWidth())
		self.Form_MCfit.setSizePolicy(sizePolicy)
		self.Form_MCfit.setObjectName("Form_MCfit")
		self.formLayout_9 = QtWidgets.QFormLayout(self.Form_MCfit)
		self.formLayout_9.setLabelAlignment(QtCore.Qt.AlignCenter)
		self.formLayout_9.setObjectName("formLayout_9")
		
		self.label_c = QtWidgets.QLabel(self.Form_MCfit)
		self.label_c.setObjectName("label_c")
		self.formLayout_9.setWidget(0, QtWidgets.QFormLayout.LabelRole, self.label_c)
		self.value_c = QtWidgets.QLabel(self.Form_MCfit)
		self.value_c.setObjectName("value_c")
		self.formLayout_9.setWidget(0, QtWidgets.QFormLayout.FieldRole, self.value_c)
		
		self.label_phi = QtWidgets.QLabel(self.Form_MCfit)
		self.label_phi.setObjectName("label_phi")
		self.formLayout_9.setWidget(1, QtWidgets.QFormLayout.LabelRole, self.label_phi)
		self.value_phi = QtWidgets.QLabel(self.Form_MCfit)
		self.value_phi.setObjectName("value_phi")
		self.formLayout_9.setWidget(1, QtWidgets.QFormLayout.FieldRole, self.value_phi)
		
		self.label_s1max = QtWidgets.QLabel(self.Form_MCfit)
		self.label_s1max.setObjectName("label_s1max")
		self.formLayout_9.setWidget(2, QtWidgets.QFormLayout.LabelRole, self.label_s1max)
		
		self.value_s1max = QtWidgets.QLabel(self.Form_MCfit)
		self.value_s1max.setObjectName("value_s1max")
		self.formLayout_9.setWidget(2, QtWidgets.QFormLayout.FieldRole, self.value_s1max)
		
		self.label_deviatoric = QtWidgets.QLabel(self.Form_MCfit)
		self.label_deviatoric.setObjectName("label_deviatoric")
		self.formLayout_9.setWidget(3, QtWidgets.QFormLayout.LabelRole, self.label_deviatoric)
		
		self.value_deviatoric = QtWidgets.QLabel(self.Form_MCfit)
		self.value_deviatoric.setObjectName("value_deviatoric")
		self.formLayout_9.setWidget(3, QtWidgets.QFormLayout.FieldRole, self.value_deviatoric)
		
		
		self.label_fail = QtWidgets.QLabel(self.Form_MCfit)
		self.label_fail.setObjectName("label_fail")
		self.formLayout_9.setWidget(4, QtWidgets.QFormLayout.LabelRole, self.label_fail)
		
		self.value_fail = QtWidgets.QLabel(self.Form_MCfit)
		self.value_fail.setObjectName("value_fail")
		self.formLayout_9.setWidget(4, QtWidgets.QFormLayout.FieldRole, self.value_fail)

		
		self.verticalLayout_5.addWidget(self.Form_MCfit, 0, QtCore.Qt.AlignHCenter)
		self.verticalLayout_2.addWidget(self.frame_MCfit, 0, QtCore.Qt.AlignHCenter)
		self.rock_mass = QtWidgets.QLabel(self.output_param)
		self.rock_mass.setObjectName("rock_mass")
		self.verticalLayout_2.addWidget(self.rock_mass, 0, QtCore.Qt.AlignHCenter)
		self.frame_rockmass = QtWidgets.QFrame(self.output_param)
		self.frame_rockmass.setFrameShape(QtWidgets.QFrame.Box)
		self.frame_rockmass.setFrameShadow(QtWidgets.QFrame.Plain)
		self.frame_rockmass.setObjectName("frame_rockmass")
		self.verticalLayout_6 = QtWidgets.QVBoxLayout(self.frame_rockmass)
		self.verticalLayout_6.setObjectName("verticalLayout_6")
		self.Form_rockmass = QtWidgets.QWidget(self.frame_rockmass)
		sizePolicy = QtWidgets.QSizePolicy(QtWidgets.QSizePolicy.Fixed, QtWidgets.QSizePolicy.Fixed)
		sizePolicy.setHorizontalStretch(0)
		sizePolicy.setVerticalStretch(0)
		sizePolicy.setHeightForWidth(self.Form_rockmass.sizePolicy().hasHeightForWidth())
		self.Form_rockmass.setSizePolicy(sizePolicy)
		self.Form_rockmass.setAutoFillBackground(False)
		self.Form_rockmass.setObjectName("Form_rockmass")
		self.formLayout_10 = QtWidgets.QFormLayout(self.Form_rockmass)
		self.formLayout_10.setLabelAlignment(QtCore.Qt.AlignCenter)
		self.formLayout_10.setObjectName("formLayout_10")
		self.label_st = QtWidgets.QLabel(self.Form_rockmass)
		self.label_st.setObjectName("label_st")
		self.formLayout_10.setWidget(0, QtWidgets.QFormLayout.LabelRole, self.label_st)
		self.label_su = QtWidgets.QLabel(self.Form_rockmass)
		self.label_su.setObjectName("label_su")
		self.formLayout_10.setWidget(1, QtWidgets.QFormLayout.LabelRole, self.label_su)
		self.label_scm = QtWidgets.QLabel(self.Form_rockmass)
		self.label_scm.setObjectName("label_scm")
		self.formLayout_10.setWidget(2, QtWidgets.QFormLayout.LabelRole, self.label_scm)
		
		self.value_st = QtWidgets.QLabel(self.Form_rockmass)
		self.value_st.setObjectName("value_st")
		self.formLayout_10.setWidget(0, QtWidgets.QFormLayout.FieldRole, self.value_st)
		
		self.value_su = QtWidgets.QLabel(self.Form_rockmass)
		self.value_su.setObjectName("value_su")
		self.formLayout_10.setWidget(1, QtWidgets.QFormLayout.FieldRole, self.value_su)
		
		self.value_scm = QtWidgets.QLabel(self.Form_rockmass)
		self.value_scm.setObjectName("value_scm")
		self.formLayout_10.setWidget(2, QtWidgets.QFormLayout.FieldRole, self.value_scm)
		
		self.label_erm = QtWidgets.QLabel(self.Form_rockmass)
		self.label_erm.setObjectName("label_erm")
		self.formLayout_10.setWidget(3, QtWidgets.QFormLayout.LabelRole, self.label_erm)

		self.value_erm = QtWidgets.QLabel(self.Form_rockmass)
		self.value_erm.setObjectName("value_erm")
		self.formLayout_10.setWidget(3, QtWidgets.QFormLayout.FieldRole, self.value_erm)
		
		self.verticalLayout_6.addWidget(self.Form_rockmass)
		self.verticalLayout_2.addWidget(self.frame_rockmass, 0, QtCore.Qt.AlignHCenter)
		self.gridLayout.addWidget(self.output_param, 0, 2, 1, 1)
		self.input_param = QtWidgets.QWidget(self.main_grid)
		self.input_param.setEnabled(True)
		sizePolicy = QtWidgets.QSizePolicy(QtWidgets.QSizePolicy.Fixed, QtWidgets.QSizePolicy.Fixed)
		sizePolicy.setHorizontalStretch(0)
		sizePolicy.setVerticalStretch(0)
		sizePolicy.setHeightForWidth(self.input_param.sizePolicy().hasHeightForWidth())
		self.input_param.setSizePolicy(sizePolicy)
		self.input_param.setObjectName("input_param")
		self.verticalLayout = QtWidgets.QVBoxLayout(self.input_param)
		self.verticalLayout.setObjectName("verticalLayout")
		self.HB_class_2 = QtWidgets.QLabel(self.input_param)
		sizePolicy = QtWidgets.QSizePolicy(QtWidgets.QSizePolicy.Fixed, QtWidgets.QSizePolicy.Fixed)
		sizePolicy.setHorizontalStretch(0)
		sizePolicy.setVerticalStretch(0)
		sizePolicy.setHeightForWidth(self.HB_class_2.sizePolicy().hasHeightForWidth())
		self.HB_class_2.setSizePolicy(sizePolicy)
		self.HB_class_2.setWordWrap(True)
		self.HB_class_2.setObjectName("HB_class_2")
		self.verticalLayout.addWidget(self.HB_class_2, 0, QtCore.Qt.AlignHCenter|QtCore.Qt.AlignVCenter)
		self.frame_HBclass = QtWidgets.QFrame(self.input_param)
		sizePolicy = QtWidgets.QSizePolicy(QtWidgets.QSizePolicy.Fixed, QtWidgets.QSizePolicy.Preferred)
		sizePolicy.setHorizontalStretch(0)
		sizePolicy.setVerticalStretch(0)
		sizePolicy.setHeightForWidth(self.frame_HBclass.sizePolicy().hasHeightForWidth())
		self.frame_HBclass.setSizePolicy(sizePolicy)
		self.frame_HBclass.setFrameShape(QtWidgets.QFrame.Box)
		self.frame_HBclass.setFrameShadow(QtWidgets.QFrame.Plain)
		self.frame_HBclass.setObjectName("frame_HBclass")
		self.verticalLayout_7 = QtWidgets.QVBoxLayout(self.frame_HBclass)
		self.verticalLayout_7.setObjectName("verticalLayout_7")
		self.HB_class = QtWidgets.QWidget(self.frame_HBclass)
		sizePolicy = QtWidgets.QSizePolicy(QtWidgets.QSizePolicy.Fixed, QtWidgets.QSizePolicy.Fixed)
		sizePolicy.setHorizontalStretch(0)
		sizePolicy.setVerticalStretch(0)
		sizePolicy.setHeightForWidth(self.HB_class.sizePolicy().hasHeightForWidth())
		self.HB_class.setSizePolicy(sizePolicy)
		self.HB_class.setObjectName("HB_class")
		self.formLayout = QtWidgets.QFormLayout(self.HB_class)
		self.formLayout.setObjectName("formLayout")
		self.label_sci = QtWidgets.QLabel(self.HB_class)
		self.label_sci.setObjectName("label_sci")
		self.formLayout.setWidget(0, QtWidgets.QFormLayout.LabelRole, self.label_sci)
		self.label_mi = QtWidgets.QLabel(self.HB_class)
		self.label_mi.setObjectName("label_mi")
		self.formLayout.setWidget(1, QtWidgets.QFormLayout.LabelRole, self.label_mi)
		self.label_GSI = QtWidgets.QLabel(self.HB_class)
		self.label_GSI.setObjectName("label_GSI")
		self.formLayout.setWidget(2, QtWidgets.QFormLayout.LabelRole, self.label_GSI)
		self.label_D = QtWidgets.QLabel(self.HB_class)
		self.label_D.setObjectName("label_D")
		self.formLayout.setWidget(3, QtWidgets.QFormLayout.LabelRole, self.label_D)
		self.label_Ei = QtWidgets.QLabel(self.HB_class)
		self.label_Ei.setObjectName("label_Ei")
		self.formLayout.setWidget(4, QtWidgets.QFormLayout.LabelRole, self.label_Ei)
		self.label_MR = QtWidgets.QLabel(self.HB_class)
		self.label_MR.setObjectName("label_MR")
		self.formLayout.setWidget(5, QtWidgets.QFormLayout.LabelRole, self.label_MR)
		
		self.value_sci = QtWidgets.QLineEdit(self.HB_class)
		self.value_sci.setObjectName("value_sci")
		self.formLayout.setWidget(0, QtWidgets.QFormLayout.FieldRole, self.value_sci)
		self.value_sci.editingFinished.connect(lambda: self.value_change(self.value_sci.objectName(),self.value_sci.text()))
		
		self.value_mi = QtWidgets.QLineEdit(self.HB_class)
		self.value_mi.setObjectName("value_mi")
		self.formLayout.setWidget(1, QtWidgets.QFormLayout.FieldRole, self.value_mi)
		self.value_mi.editingFinished.connect(lambda: self.value_change(self.value_mi.objectName(),self.value_mi.text()))
		
		self.value_GSI = QtWidgets.QLineEdit(self.HB_class)
		self.value_GSI.setObjectName("value_GSI")
		self.formLayout.setWidget(2, QtWidgets.QFormLayout.FieldRole, self.value_GSI)
		self.value_GSI.editingFinished.connect(lambda: self.value_change(self.value_GSI.objectName(),self.value_GSI.text()))
		
		self.value_D = QtWidgets.QLineEdit(self.HB_class)
		self.value_D.setObjectName("value_D")
		self.formLayout.setWidget(3, QtWidgets.QFormLayout.FieldRole, self.value_D)
		self.value_D.editingFinished.connect(lambda: self.value_change(self.value_D.objectName(),self.value_D.text()))
		
		self.form_Ei = QtWidgets.QFormLayout()
		self.form_Ei.setLabelAlignment(QtCore.Qt.AlignCenter)
		self.form_Ei.setObjectName("form_Ei")
		self.value_Ei = QtWidgets.QLineEdit(self.HB_class)
		self.value_Ei.setEnabled(False)
		self.value_Ei.setObjectName("value_Ei")
		self.form_Ei.setWidget(0, QtWidgets.QFormLayout.LabelRole, self.value_Ei)
		self.value_Ei.editingFinished.connect(lambda: self.value_change(self.value_Ei.objectName(),self.value_Ei.text()))
		
		self.calc_Ei = QtWidgets.QCheckBox(self.HB_class)
		sizePolicy = QtWidgets.QSizePolicy(QtWidgets.QSizePolicy.Minimum, QtWidgets.QSizePolicy.Fixed)
		sizePolicy.setHorizontalStretch(0)
		sizePolicy.setVerticalStretch(0)
		sizePolicy.setHeightForWidth(self.calc_Ei.sizePolicy().hasHeightForWidth())
		self.calc_Ei.setSizePolicy(sizePolicy)
		self.calc_Ei.setText("")
		self.calc_Ei.setIconSize(QtCore.QSize(16, 16))
		self.calc_Ei.setObjectName("calc_Ei")
		self.calc_Ei.stateChanged.connect(lambda: self.check_change(self.calc_Ei.objectName(),self.calc_Ei.checkState()))
		self.form_Ei.setWidget(0, QtWidgets.QFormLayout.FieldRole, self.calc_Ei)
		self.formLayout.setLayout(4, QtWidgets.QFormLayout.FieldRole, self.form_Ei)
		
		self.form_MR = QtWidgets.QFormLayout()
		self.form_MR.setLabelAlignment(QtCore.Qt.AlignCenter)
		self.form_MR.setObjectName("form_MR")
		self.value_MR = QtWidgets.QLineEdit(self.HB_class)
		self.value_MR.setObjectName("value_MR")
		self.form_MR.setWidget(0, QtWidgets.QFormLayout.LabelRole, self.value_MR)
		self.value_MR.editingFinished.connect(lambda: self.value_change(self.value_MR.objectName(),self.value_MR.text()))
		
		self.calc_MR = QtWidgets.QCheckBox(self.HB_class)
		sizePolicy = QtWidgets.QSizePolicy(QtWidgets.QSizePolicy.Minimum, QtWidgets.QSizePolicy.Fixed)
		sizePolicy.setHorizontalStretch(0)
		sizePolicy.setVerticalStretch(0)
		sizePolicy.setHeightForWidth(self.calc_MR.sizePolicy().hasHeightForWidth())
		self.calc_MR.setSizePolicy(sizePolicy)
		self.calc_MR.setText("")
		self.calc_MR.setIconSize(QtCore.QSize(16, 16))
		self.calc_MR.setObjectName("calc_MR")
		self.calc_MR.setChecked(True)
		self.calc_MR.stateChanged.connect(lambda: self.check_change(self.calc_MR.objectName(),self.calc_MR.checkState()))
		
		self.form_MR.setWidget(0, QtWidgets.QFormLayout.FieldRole, self.calc_MR)
		self.formLayout.setLayout(5, QtWidgets.QFormLayout.FieldRole, self.form_MR)
		self.verticalLayout_7.addWidget(self.HB_class)
		
		self.update_form(self.HB_class.findChildren(QtWidgets.QLineEdit),HB_in)

		
		
		self.verticalLayout.addWidget(self.frame_HBclass, 0, QtCore.Qt.AlignHCenter)
		self.fail_env = QtWidgets.QLabel(self.input_param)
		sizePolicy = QtWidgets.QSizePolicy(QtWidgets.QSizePolicy.Fixed, QtWidgets.QSizePolicy.Fixed)
		sizePolicy.setHorizontalStretch(0)
		sizePolicy.setVerticalStretch(0)
		sizePolicy.setHeightForWidth(self.fail_env.sizePolicy().hasHeightForWidth())
		self.fail_env.setSizePolicy(sizePolicy)
		self.fail_env.setWordWrap(True)
		self.fail_env.setObjectName("fail_env")
		self.verticalLayout.addWidget(self.fail_env, 0, QtCore.Qt.AlignHCenter)
		self.frame_5 = QtWidgets.QFrame(self.input_param)
		sizePolicy = QtWidgets.QSizePolicy(QtWidgets.QSizePolicy.Fixed, QtWidgets.QSizePolicy.Preferred)
		sizePolicy.setHorizontalStretch(0)
		sizePolicy.setVerticalStretch(0)
		sizePolicy.setHeightForWidth(self.frame_5.sizePolicy().hasHeightForWidth())
		self.frame_5.setSizePolicy(sizePolicy)
		self.frame_5.setFrameShape(QtWidgets.QFrame.Box)
		self.frame_5.setFrameShadow(QtWidgets.QFrame.Plain)
		self.frame_5.setObjectName("frame_5")
		self.horizontalLayout_2 = QtWidgets.QHBoxLayout(self.frame_5)
		self.horizontalLayout_2.setObjectName("horizontalLayout_2")
		self.fenv = QtWidgets.QWidget(self.frame_5)
		sizePolicy = QtWidgets.QSizePolicy(QtWidgets.QSizePolicy.Minimum, QtWidgets.QSizePolicy.Fixed)
		sizePolicy.setHorizontalStretch(0)
		sizePolicy.setVerticalStretch(0)
		sizePolicy.setHeightForWidth(self.fenv.sizePolicy().hasHeightForWidth())
		self.fenv.setSizePolicy(sizePolicy)
		self.fenv.setObjectName("fenv")
		self.formLayout_2 = QtWidgets.QFormLayout(self.fenv)
		self.formLayout_2.setObjectName("formLayout_2")
		self.label_app = QtWidgets.QLabel(self.fenv)
		self.label_app.setObjectName("label_app")
		self.formLayout_2.setWidget(0, QtWidgets.QFormLayout.LabelRole, self.label_app)
		self.label_gamma = QtWidgets.QLabel(self.fenv)
		self.label_gamma.setObjectName("label_gamma")
		self.formLayout_2.setWidget(1, QtWidgets.QFormLayout.LabelRole, self.label_gamma)
		
		self.value_appl = QtWidgets.QComboBox(self.fenv)
		self.value_appl.setObjectName("value_appl")
		self.value_appl.addItem("")
		self.value_appl.addItem("")
		self.value_appl.addItem("")
		self.value_appl.addItem("")
		self.formLayout_2.setWidget(0, QtWidgets.QFormLayout.FieldRole, self.value_appl)
		self.value_appl.activated.connect(lambda: self.value_appl_change(self.value_appl.objectName(),self.value_appl.currentText()))
		
		self.value_gamma = QtWidgets.QLineEdit(self.fenv)
		self.value_gamma.setEnabled(False)
		self.value_gamma.setObjectName("value_gamma")
		self.formLayout_2.setWidget(1, QtWidgets.QFormLayout.FieldRole, self.value_gamma)
		self.value_gamma.editingFinished.connect(lambda: self.value_changefail(self.value_appl.currentText(),self.value_gamma.objectName(),self.value_gamma.text()))
		
		self.label_H = QtWidgets.QLabel(self.fenv)
		self.label_H.setObjectName("label_H")
		self.formLayout_2.setWidget(2, QtWidgets.QFormLayout.LabelRole, self.label_H)
		self.value_H = QtWidgets.QLineEdit(self.fenv)
		self.value_H.setEnabled(False)
		self.value_H.setObjectName("value_H")
		self.formLayout_2.setWidget(2, QtWidgets.QFormLayout.FieldRole, self.value_H)
		self.value_H.editingFinished.connect(lambda: self.value_changefail(self.value_appl.currentText(),self.value_H.objectName(),self.value_H.text()))
		
		self.label_s3max = QtWidgets.QLabel(self.fenv)
		self.label_s3max.setObjectName("label_s3max")
		self.formLayout_2.setWidget(3, QtWidgets.QFormLayout.LabelRole, self.label_s3max)
		self.value_s3max = QtWidgets.QLineEdit(self.fenv)
		self.value_s3max.setEnabled(False)
		self.value_s3max.setObjectName("value_s3max")
		self.formLayout_2.setWidget(3, QtWidgets.QFormLayout.FieldRole, self.value_s3max)
		self.value_s3max.editingFinished.connect(lambda: self.value_changefail(self.value_appl.currentText(),self.value_s3max.objectName(),self.value_s3max.text()))
		
		self.horizontalLayout_2.addWidget(self.fenv)
		self.verticalLayout.addWidget(self.frame_5)
		
		self.update_form(self.fenv.findChildren(QtWidgets.QLineEdit),fail_in)
		
		self.Graph_options = QtWidgets.QLabel(self.input_param)
		self.Graph_options.setObjectName("Graph_options")
		self.verticalLayout.addWidget(self.Graph_options, 0, QtCore.Qt.AlignHCenter)
		self.graph_options = QtWidgets.QFrame(self.input_param)
		self.graph_options.setFrameShape(QtWidgets.QFrame.Box)
		self.graph_options.setFrameShadow(QtWidgets.QFrame.Plain)
		self.graph_options.setObjectName("graph_options")
		self.formLayout_3 = QtWidgets.QFormLayout(self.graph_options)
		self.formLayout_3.setObjectName("formLayout_3")
		self.label_xres = QtWidgets.QLabel(self.graph_options)
		self.label_xres.setObjectName("label_xres")
		self.formLayout_3.setWidget(0, QtWidgets.QFormLayout.LabelRole, self.label_xres)

		self.show_HB = QtWidgets.QCheckBox(self.graph_options)
		sizePolicy = QtWidgets.QSizePolicy(QtWidgets.QSizePolicy.Fixed, QtWidgets.QSizePolicy.Preferred)
		sizePolicy.setHorizontalStretch(0)
		sizePolicy.setVerticalStretch(0)
		sizePolicy.setHeightForWidth(self.show_HB.sizePolicy().hasHeightForWidth())
		self.show_HB.setSizePolicy(sizePolicy)
		self.show_HB.setChecked(True)
		self.show_HB.setAutoExclusive(False)
		self.show_HB.setObjectName("show_HB")
		self.formLayout_3.setWidget(1, QtWidgets.QFormLayout.FieldRole, self.show_HB)
		self.show_HB.stateChanged.connect(lambda: self.options_check(self.show_HB.objectName(),self.show_HB.checkState()))
		
		self.show_MC = QtWidgets.QCheckBox(self.graph_options)
		sizePolicy = QtWidgets.QSizePolicy(QtWidgets.QSizePolicy.Fixed, QtWidgets.QSizePolicy.Preferred)
		sizePolicy.setHorizontalStretch(0)
		sizePolicy.setVerticalStretch(0)
		sizePolicy.setHeightForWidth(self.show_MC.sizePolicy().hasHeightForWidth())
		self.show_MC.setSizePolicy(sizePolicy)
		self.show_MC.setObjectName("show_MC")
		self.formLayout_3.setWidget(2, QtWidgets.QFormLayout.FieldRole, self.show_MC)
		self.show_MC.stateChanged.connect(lambda: self.options_check(self.show_MC.objectName(),self.show_MC.checkState()))

		self.show_grid = QtWidgets.QCheckBox(self.graph_options)
		sizePolicy = QtWidgets.QSizePolicy(QtWidgets.QSizePolicy.Fixed, QtWidgets.QSizePolicy.Preferred)
		sizePolicy.setHorizontalStretch(0)
		sizePolicy.setVerticalStretch(0)
		sizePolicy.setHeightForWidth(self.show_MC.sizePolicy().hasHeightForWidth())
		self.show_grid.setSizePolicy(sizePolicy)
		self.show_grid.setChecked(True)
		self.show_grid.setObjectName("show_grid")
		self.formLayout_3.setWidget(3, QtWidgets.QFormLayout.FieldRole, self.show_grid)
		self.show_grid.stateChanged.connect(lambda: self.options_check(self.show_grid.objectName(),self.show_grid.checkState()))

		self.value_xres = QtWidgets.QDoubleSpinBox(self.graph_options)
		sizePolicy = QtWidgets.QSizePolicy(QtWidgets.QSizePolicy.Fixed, QtWidgets.QSizePolicy.Preferred)
		sizePolicy.setHorizontalStretch(0)
		sizePolicy.setVerticalStretch(0)
		sizePolicy.setHeightForWidth(self.value_xres.sizePolicy().hasHeightForWidth())
		self.value_xres.setSizePolicy(sizePolicy)
		self.value_xres.setStepType(QtWidgets.QAbstractSpinBox.DefaultStepType)
		self.value_xres.setProperty("value", 5.0)
		self.value_xres.setObjectName("value_xres")
		self.formLayout_3.setWidget(0, QtWidgets.QFormLayout.FieldRole, self.value_xres)
		self.value_xres.valueChanged.connect(lambda: self.value_changegraph(self.value_xres.objectName(),self.value_xres.text()))
		
		self.verticalLayout.addWidget(self.graph_options)
		self.gridLayout.addWidget(self.input_param, 0, 0, 1, 1)
		self.verticalLayout_3.addWidget(self.main_grid)
		


		
		self.Plot = QtWidgets.QTabWidget(self.main_grid)
		sizePolicy = QtWidgets.QSizePolicy(QtWidgets.QSizePolicy.Expanding, QtWidgets.QSizePolicy.Expanding)
		sizePolicy.setHorizontalStretch(0)
		sizePolicy.setVerticalStretch(0)
		sizePolicy.setHeightForWidth(self.Plot.sizePolicy().hasHeightForWidth())
		self.Plot.setSizePolicy(sizePolicy)
		self.Plot.setMinimumSize(QtCore.QSize(622, 644))
		self.Plot.setObjectName("Plot")
		self.PlotPage1 = QtWidgets.QWidget()
		self.PlotPage1.setObjectName("PlotPage1")
		self.Plot.addTab(self.PlotPage1, "H-B criterion")
		self.PlotPage2 = QtWidgets.QWidget()
		sizePolicy = QtWidgets.QSizePolicy(QtWidgets.QSizePolicy.Preferred, QtWidgets.QSizePolicy.Preferred)
		sizePolicy.setHorizontalStretch(0)
		sizePolicy.setVerticalStretch(0)
		sizePolicy.setHeightForWidth(self.PlotPage2.sizePolicy().hasHeightForWidth())
		self.PlotPage2.setSizePolicy(sizePolicy)
		self.PlotPage2.setObjectName("PlotPage2")
		self.Plot.addTab(self.PlotPage2, "M-C circle")
		self.gridLayout.addWidget(self.Plot, 0, 1, 1, 1)
		self.verticalLayout_3.addWidget(self.main_grid)
		Rocpy.setCentralWidget(self.main_window)
		self.menu_bar = QtWidgets.QMenuBar(Rocpy)
		self.menu_bar.setGeometry(QtCore.QRect(0, 0, 1125, 22))
		self.menu_bar.setObjectName("menu_bar")
		self.menu_Import = QtWidgets.QMenu(self.menu_bar)
		self.menu_Import.setObjectName("menu_Import")
		self.menu_Export = QtWidgets.QMenu(self.menu_bar)
		self.menu_Export.setObjectName("menu_Export")
		Rocpy.setMenuBar(self.menu_bar)

		self.actionExport_graph = QtWidgets.QAction(Rocpy)
		self.actionExport_graph.setObjectName("actionExport_graph")
		self.actionExport_data = QtWidgets.QAction(Rocpy)
		self.actionExport_data.setObjectName("actionExport_data")
		self.menu_Export.addSeparator()
		self.menu_Export.addAction(self.actionExport_graph)
		self.menu_Export.addAction(self.actionExport_data)
		self.menu_bar.addAction(self.menu_Import.menuAction())
		self.menu_bar.addAction(self.menu_Export.menuAction())

		self.retranslateUi(Rocpy)
		QtCore.QMetaObject.connectSlotsByName(Rocpy)

		self.canvHB = pltCanvas(self)
		
		ut.plot_HB(self,HB_in, HB_out, rockmass_out,mohr_out,graph_opt)


		self.toolbarHB = NavigationToolbar(self.canvHB,self.PlotPage1)
		self.Pg1_layout = QtWidgets.QVBoxLayout(self.PlotPage1)
		self.Pg1_layout.addWidget(self.canvHB)
		self.Pg1_layout.addWidget(self.toolbarHB)
		
		
		self.canvMC = pltCanvas(self)
		self.toolbarMC = NavigationToolbar(self.canvMC,self.PlotPage1)
		self.Pg2_layout = QtWidgets.QVBoxLayout(self.PlotPage2)
		self.Pg2_layout.addWidget(self.canvMC)
		self.Pg2_layout.addWidget(self.toolbarMC)
		ut.plot_MC_circle(self,fail_in,mohr_out)
		#self.canvHB.draw()
		

	#@profile
	def retranslateUi(self, Rocpy):

		_translate = QtCore.QCoreApplication.translate
		Rocpy.setWindowTitle(_translate("Rocpy", "Rocpy"))
		self.HB_crit.setText(_translate("Rocpy", "H-B criterion"))
		self.label_mb.setText(_translate("Rocpy", "mb:"))
		self.label_s.setText(_translate("Rocpy", "s:"))
		self.label_a.setText(_translate("Rocpy", "a:"))
		
		
		self.update_form(self.form_HBcrit.findChildren(QtWidgets.QLabel),HB_out,1)
		
		self.MC_fit_2.setText(_translate("Rocpy", "M-C circle"))
		self.label_c.setText(_translate("Rocpy", "c:"))
		self.value_c.setText(_translate("Rocpy", "TextLabel"))
		self.label_phi.setText(_translate("Rocpy", "phi:"))
		self.value_phi.setText(_translate("Rocpy", "TextLabel"))
		self.label_s1max.setText(_translate("Rocpy", "s_1max:"))
		self.value_s1max.setText(_translate("Rocpy", "TextLabel"))
		self.label_deviatoric.setText(_translate("Rocpy", "Deviatoric:"))
		self.value_deviatoric.setText(_translate("Rocpy", "TextLabel"))

		self.label_fail.setText(_translate("Rocpy", "Failure values: "))
		self.value_fail.setText(_translate("Rocpy", "TextLabel"))


		self.update_form(self.Form_MCfit.findChildren(QtWidgets.QLabel),mohr_out,1)
		
		self.rock_mass.setText(_translate("Rocpy", "Rock mass parameters"))
		self.label_st.setText(_translate("Rocpy", "s_t:"))
		self.label_su.setText(_translate("Rocpy", "s_u:"))
		self.label_scm.setText(_translate("Rocpy", "s_cm:"))
		self.value_st.setText(_translate("Rocpy", "test"))
		self.value_su.setText(_translate("Rocpy", "TextLabel"))
		self.value_scm.setText(_translate("Rocpy", "TextLabel"))
		self.label_erm.setText(_translate("Rocpy", "E_rm:"))
		self.value_erm.setText(_translate("Rocpy", "TextLabel"))

		
		self.update_form(self.Form_rockmass.findChildren(QtWidgets.QLabel),rockmass_out,1)

		
		self.HB_class_2.setText(_translate("Rocpy", "H-B classification"))
		self.label_sci.setText(_translate("Rocpy", "s_ci"))
		self.label_mi.setText(_translate("Rocpy", "mi"))
		self.label_GSI.setText(_translate("Rocpy", "GSI"))
		self.label_D.setText(_translate("Rocpy", "D"))
		self.label_Ei.setText(_translate("Rocpy", "E_i"))
		self.label_MR.setText(_translate("Rocpy", "MR"))
		self.fail_env.setText(_translate("Rocpy", "Failure envelope"))
		self.label_app.setText(_translate("Rocpy", "application"))
		self.label_gamma.setText(_translate("Rocpy", "gamma"))
		self.label_H.setText(_translate("Rocpy", "H"))
		self.label_s3max.setText(_translate("Rocpy", "s_3max"))
		self.Graph_options.setText(_translate("Rocpy", "H-B criterion graph options"))
		self.label_xres.setText(_translate("Rocpy", "x_res"))
		self.show_HB.setText(_translate("Rocpy", "Show H-B criterion"))
		self.show_MC.setText(_translate("Rocpy", "Show M-C criterion"))
		self.show_grid.setText(_translate("Rocpy", "Show grid"))
		self.value_appl.setItemText(0, _translate("Rocpy", "general"))
		self.value_appl.setItemText(1, _translate("Rocpy", "tunnel"))
		self.value_appl.setItemText(2, _translate("Rocpy", "slope"))
		self.value_appl.setItemText(3, _translate("Rocpy", "custom"))
		self.menu_Import.setTitle(_translate("Rocpy", "Import"))
		self.menu_Export.setTitle(_translate("Rocpy", "Export"))

		self.actionExport_graph.setText(_translate("Rocpy", "Export graph"))
		self.actionExport_data.setText(_translate("Rocpy", "Export data"))
	
	#@profile
	def value_change(self,name,text):
	
		if self.inQueue.not_empty:
			try:
				self.consoleWindow.append(self.inQueue.get_nowait())
			except:
				True
	
		HB_in[name] = float(text)
		

		
		
		if self.calc_MR.checkState():	
			HB_in['value_Ei'] = HB_in['value_MR']*HB_in['value_sci']
			self.value_Ei.setText(str(round(HB_in['value_Ei'],3)))
		else:
			HB_in['value_MR'] = HB_in['value_Ei']/HB_in['value_sci']
			self.value_MR.setText(str(round(HB_in['value_MR'],3)))
		

		HB_out = ut.calc_HB(HB_in)
		mohr_out = ut.calc_MC(HB_in,fail_in,HB_out)
		rockmass_out = ut.calc_rockm(HB_in,HB_out)
		
		self.update_form(self.HB_class.findChildren(QtWidgets.QLineEdit),HB_in)
		self.update_form(self.fenv.findChildren(QtWidgets.QLineEdit),fail_in,1)
		self.update_form(self.form_HBcrit.findChildren(QtWidgets.QLabel),HB_out,1)
		self.update_form(self.Form_MCfit.findChildren(QtWidgets.QLabel),mohr_out,1)
		self.update_form(self.Form_rockmass.findChildren(QtWidgets.QLabel),rockmass_out,1)
		
		ut.plot_HB(self,HB_in, HB_out, rockmass_out,mohr_out,graph_opt)
		ut.plot_MC_circle(self,fail_in,mohr_out)
		#self.update_forms(forms_opt_list)
	
	#@profile
	def value_changefail(self,method, name, text):
		
		if self.inQueue.not_empty:
			try:
				self.consoleWindow.append(self.inQueue.get_nowait())
			except:
				True
	
		fail_in[name] = float(text)

		HB_out = ut.calc_HB(HB_in)

		rockmass_out = ut.calc_rockm(HB_in,HB_out)
		if method == 'tunnel':
			fail_in['value_s3max'] = 0.47*power(rockmass_out['value_scm']/(fail_in['value_gamma']*fail_in['value_H']),-0.94)*rockmass_out['value_scm']
		elif method == 'slope':
			fail_in['value_s3max'] = 0.72*power(rockmass_out['value_scm']/(fail_in['value_gamma']*fail_in['value_H']),-0.91)*rockmass_out['value_scm']
		elif method == 'general':
			fail_in['value_s3max'] = HB_in['value_sci']/4
		elif method == 'custom':
			fail_in['value_s3max'] = float(text)

		mohr_out = ut.calc_MC(HB_in,fail_in,HB_out)
		
		self.update_form(self.HB_class.findChildren(QtWidgets.QLineEdit),HB_in)
		self.update_form(self.fenv.findChildren(QtWidgets.QLineEdit),fail_in,1)
		
		self.update_form(self.form_HBcrit.findChildren(QtWidgets.QLabel),HB_out,1)
		self.update_form(self.Form_MCfit.findChildren(QtWidgets.QLabel),mohr_out,1)
		self.update_form(self.Form_rockmass.findChildren(QtWidgets.QLabel),rockmass_out,1)
		
		ut.plot_HB(self,HB_in, HB_out, rockmass_out,mohr_out,graph_opt)
		ut.plot_MC_circle(self,fail_in,mohr_out)
		#self.update_forms(forms_opt_list)
	
	
		
	#@profile
	def check_change(self,name,value):
	
		if name == 'calc_MR':
			if value:
				
				self.calc_Ei.setChecked(False)
				self.value_Ei.setEnabled(False)
				self.value_MR.setEnabled(True)
			else:
				self.calc_Ei.setChecked(True)
				self.value_Ei.setEnabled(True)
				self.value_MR.setEnabled(False)
				
		elif name== 'calc_Ei':
			if value:
				self.calc_MR.setChecked(False) #we don't need to change the state of value because it's taken care of the calc_MR state change 

			else:
				self.calc_MR.setChecked(True)

	#@profile
	def value_changegraph(self,name,text):
		
		if self.inQueue.not_empty:
			try:
				self.consoleWindow.append(self.inQueue.get_nowait())
			except:
				True
	
		HB_out = ut.calc_HB(HB_in)
		mohr_out = ut.calc_MC(HB_in,fail_in,HB_out)
		rockmass_out = ut.calc_rockm(HB_in,HB_out)
		graph_opt[name] = text.replace(',','.')
		ut.plot_HB(self,HB_in, HB_out, rockmass_out,mohr_out,graph_opt)
	
	#@profile
	def options_check(self,name,value):
		
		if self.inQueue.not_empty:
			try:
				self.consoleWindow.append(self.inQueue.get_nowait())
			except:
				True
	
		HB_out = ut.calc_HB(HB_in)
		mohr_out = ut.calc_MC(HB_in,fail_in,HB_out)
		rockmass_out = ut.calc_rockm(HB_in,HB_out)
				
		graph_opt[name] = value
		ut.plot_HB(self,HB_in, HB_out, rockmass_out,mohr_out,graph_opt)
	
	#@profile
	def value_appl_change(self,name,text):
		
		if self.inQueue.not_empty:
			try:
				self.consoleWindow.append(self.inQueue.get_nowait())
			except:
				True
		
		fail_in[name] = text

		HB_out = ut.calc_HB(HB_in)
		rockmass_out = ut.calc_rockm(HB_in,HB_out)
		if text == 'general':
			self.value_gamma.setEnabled(False)
			self.value_H.setEnabled(False)
			self.value_s3max.setEnabled(False)
			fail_in['value_s3max'] = HB_in['value_sci']/4
			
		elif text == 'tunnel':
			self.value_gamma.setEnabled(True)
			self.value_H.setEnabled(True)
			self.value_s3max.setEnabled(False)
			fail_in['value_s3max'] = 0.47*power(rockmass_out['value_scm']/(fail_in['value_gamma']*fail_in['value_H']),-0.94)*rockmass_out['value_scm'] 
		elif text == 'slope':
			self.value_gamma.setEnabled(True)
			self.value_H.setEnabled(True)
			self.value_s3max.setEnabled(False)
			fail_in['value_s3max'] = 0.72*power(rockmass_out['value_scm']/(fail_in['value_gamma']*fail_in['value_H']),-0.91)*rockmass_out['value_scm'] 
		elif text == 'custom':
			self.value_gamma.setEnabled(False)
			self.value_H.setEnabled(False)
			self.value_s3max.setEnabled(True)
			fail_in['value_s3max'] = float(self.value_s3max.text())

		mohr_out = ut.calc_MC(HB_in,fail_in,HB_out)
		self.update_form(self.HB_class.findChildren(QtWidgets.QLineEdit),HB_in)
		self.update_form(self.fenv.findChildren(QtWidgets.QLineEdit),fail_in,1)
		
		self.update_form(self.form_HBcrit.findChildren(QtWidgets.QLabel),HB_out,1)
		self.update_form(self.Form_MCfit.findChildren(QtWidgets.QLabel),mohr_out,1)
		self.update_form(self.Form_rockmass.findChildren(QtWidgets.QLabel),rockmass_out,1)
		
		ut.plot_HB(self,HB_in, HB_out, rockmass_out,mohr_out,graph_opt)
		ut.plot_MC_circle(self,fail_in,mohr_out)
		#self.update_forms(forms_opt_list)

	
	
	
	#@profile
	def update_form(self,form,read_dict,approx=0): #function used to update different entries (e.g mb or E_i)
		
		if self.inQueue.not_empty:
			try:
				self.consoleWindow.append(self.inQueue.get_nowait())
			except:
				True
	
		for child in form:
			string = child.objectName()
			if 'value_' in string:
				child.clear()
				
				if approx:
					child.setText(str(round(read_dict[string],3)))
				else:
					child.setText(str(read_dict[string]))
	
	
	
	
	
if __name__ == "__main__":
	    import sys
	    from darktheme.widget_template import DarkPalette 
	    app = QtWidgets.QApplication(sys.argv)
	    Rocpy = QtWidgets.QMainWindow()
	    ui = Ui_Rocpy()
	    ui.setupUi(Rocpy)
	    Rocpy.show()
	    sys.exit(app.exec_())
